@echo off

set s=%0
set s=%s:"=%
set p=%1
set p=%p:"=%

if "%p%"=="" ( goto end )

if not exist "%p%\" ( goto end )

for /F %%i in ('dir /a /b "%p%"') do ( goto end )

net session > nul 2>&1
if NOT %errorlevel% == 0 (
	goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
	echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
	set params= %*
	echo UAC.ShellExecute "cmd.exe", "/c """"" ^& "%s%" ^& """" ^& " """ ^& "%p%" ^& """""^", "", "runas", 1 >> "%temp%\getadmin.vbs"
	"%temp%\getadmin.vbs"
	del "%temp%\getadmin.vbs"
	exit /B

:gotAdmin
	pushd "%CD%"
	CD /D "%~dp0"

if exist betaOptIn (
  rem. > "%p%\betaOptin"
)

echo $DST = $args[0] > "%~dpn0.ps1"
echo $DEFAULT_PACKAGES = @('AcidBubbles.Timeline.210.var', 'DJ.NailPolish.1.var', 'DJ.TanLines.1.var', 'Jackaroo.SmartSuitJaR.1.var', 'JayC_Re-animator.Hair_Curly_Bob.1.var', 'MacGruber.Life.12.var', 'MeshedVR.3PointLightSetup.1.var', 'MeshedVR.AssetsPack.1.var', 'MeshedVR.BonusScenes.9.var', 'MeshedVR.DemoScenes.2.var', 'MeshedVR.OlderContent.1.var', 'MeshedVR.PresetsPack.2.var', 'NoOC.Clothing_SailorLingerie.2.var', 'NoStage3.Hair_Long_Upswept_Top_Bun.1.var', 'NoStage3.UnityAssetVamifier.20.var', 'Vince.Clothing_PleatedSkirtV2T.2.var', 'Xstatic.MegaParticlePack.1.var') >> "%~dpn0.ps1"
echo $LINK = @('AddonPackages\', 'Cache', 'Custom\Assets\', 'Custom\Atom\Person\Textures\', 'VaM_Data\') >> "%~dpn0.ps1"
echo $FILES = @('AddonPackages', ` >> "%~dpn0.ps1"
echo            'AddonPackagesUserPrefs', ` >> "%~dpn0.ps1"
echo            'Assets', ` >> "%~dpn0.ps1"
echo            'Cache', ` >> "%~dpn0.ps1"
echo            'Custom', ` >> "%~dpn0.ps1"
echo            'Keys', ` >> "%~dpn0.ps1"
echo            'logs', ` >> "%~dpn0.ps1"
echo            'Mono', ` >> "%~dpn0.ps1"
echo            'Saves', ` >> "%~dpn0.ps1"
echo            'VaM_Data', ` >> "%~dpn0.ps1"
echo            'Baseline Benchmark.bat', ` >> "%~dpn0.ps1"
echo            'browse_sites.json', ` >> "%~dpn0.ps1"
echo            'ClothSim Benchmark.bat', ` >> "%~dpn0.ps1"
echo            'config', ` >> "%~dpn0.ps1"
echo            'CPU Benchmark.bat', ` >> "%~dpn0.ps1"
echo            'CPU High Physics Benchmark.bat', ` >> "%~dpn0.ps1"
echo            'Crypt Benchmark.bat', ` >> "%~dpn0.ps1"
echo            'GPU Benchmark.bat', ` >> "%~dpn0.ps1"
echo            'Hair Benchmark.bat', ` >> "%~dpn0.ps1"
echo            'HairRender Benchmark.bat', ` >> "%~dpn0.ps1"
echo            'HairSim Benchmark.bat', ` >> "%~dpn0.ps1"
echo            'MHLab.PATCH.dll', ` >> "%~dpn0.ps1"
echo            'UnityCrashHandler64.exe', ` >> "%~dpn0.ps1"
echo            'UnityPlayer.dll', ` >> "%~dpn0.ps1"
echo            'VaM (Config).bat', ` >> "%~dpn0.ps1"
echo            'VaM (Desktop Mode).bat', ` >> "%~dpn0.ps1"
echo            'VaM (OpenVR).bat', ` >> "%~dpn0.ps1"
echo            'VaM.exe', ` >> "%~dpn0.ps1"
echo            'VaM_Updater.exe', ` >> "%~dpn0.ps1"
echo            'version', ` >> "%~dpn0.ps1"
echo            'vrmanifest', ` >> "%~dpn0.ps1"
echo            'WinPixEventRuntime.dll', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\actions.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\bindings_holographic_controller.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\bindings_knuckles.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\bindings_oculus_touch.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\bindings_vive_controller.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\bindings_vive_cosmos_controller.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\binding_holographic_hmd.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\binding_rift.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\binding_vive.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\binding_vive_cosmos.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\binding_vive_pro.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\binding_vive_tracker_camera.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\binding_vive_tracker_chest.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\binding_vive_tracker_keyboard.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\binding_vive_tracker_left_foot.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\binding_vive_tracker_left_shoulder.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\binding_vive_tracker_right_foot.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\binding_vive_tracker_right_shoulder.json', ` >> "%~dpn0.ps1"
echo            'Assets\VaMAssets\SteamVR_Bindings\binding_vive_tracker_waist.json', ` >> "%~dpn0.ps1"
echo            'Custom\Assets', ` >> "%~dpn0.ps1"
echo            'Custom\Atom', ` >> "%~dpn0.ps1"
echo            'Custom\Hair', ` >> "%~dpn0.ps1"
echo            'Custom\Scripts', ` >> "%~dpn0.ps1"
echo            'Custom\Assets\MeshedVR', ` >> "%~dpn0.ps1"
echo            'Custom\Assets\MeshedVR\car_sedan.assetbundle', ` >> "%~dpn0.ps1"
echo            'Custom\Assets\MeshedVR\car_sedan.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Morphs', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Morphs\female', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Morphs\female_genitalia', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Morphs\male', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Morphs\male_genitalia', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Morphs\female\README.txt', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Morphs\female_genitalia\README.txt', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Morphs\male\README.txt', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Morphs\male_genitalia\README.txt', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\faceBrowlessD.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\faceBrowlessG.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\faceBrowlessN.tif', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\faceBrowlessS.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\faceD.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\faceDecal.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\faceG.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\faceN.tif', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\faceS.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\genitalsD.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\genitalsG.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\genitalsN.tif', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\genitalsS.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\limbsD.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\limbsG.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\limbsN.tif', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\limbsS.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\torsoD.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\torsoDecal.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\torsoG.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\torsoN.tif', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\FemaleBase\torsoS.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\faceD.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\faceDBrows.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\faceG.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\faceGbrows.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\faceN.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\faceNBrows.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\faceS.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\faceSBrows.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\genitalsD.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\genitalsG.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\genitalsN.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\genitalsS.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\limbsD.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\limbsG.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\limbsN.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\limbsS.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\torsoD.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\torsoG.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\torsoN.png', ` >> "%~dpn0.ps1"
echo            'Custom\Atom\Person\Textures\MaleBase\torsoS.png', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Male', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\RenVR', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR\Samples', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR\Samples\MohawkV3.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR\Samples\MohawkV3.vab', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR\Samples\MohawkV3.vaj', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR\Samples\MohawkV3.vam', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR\Samples\PonytailV3.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR\Samples\PonytailV3.vab', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR\Samples\PonytailV3.vaj', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR\Samples\PonytailV3.vam', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR\Samples\PubThick.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR\Samples\PubThick.vab', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR\Samples\PubThick.vaj', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\MeshedVR\Samples\PubThick.vam', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\RenVR\RenVR', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\RenVR\RenVR\Lexi Long (REN).jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\RenVR\RenVR\Lexi Long (REN).vab', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\RenVR\RenVR\Lexi Long (REN).vaj', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\RenVR\RenVR\Lexi Long (REN).vam', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\RenVR\RenVR\Simone (REN).jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\RenVR\RenVR\Simone (REN).vab', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\RenVR\RenVR\Simone (REN).vaj', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\RenVR\RenVR\Simone (REN).vam', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Adrianna_Hair.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Adrianna_Hair.vab', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Adrianna_Hair.vaj', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Adrianna_Hair.vam', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Danika_Hair.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Danika_Hair.vab', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Danika_Hair.vaj', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Danika_Hair.vam', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Izarra_Hair.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Izarra_Hair.vab', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Izarra_Hair.vaj', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Izarra_Hair.vam', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Lilith_Hair.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Lilith_Hair.vab', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Lilith_Hair.vaj', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Lilith_Hair.vam', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Norma_Hair.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Norma_Hair.vab', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Norma_Hair.vaj', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Female\VaMDeV\VaMHairstyles\Norma_Hair.vam', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Male\Jackaroo', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Male\Jackaroo\JulianBuzz.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Male\Jackaroo\JulianBuzz.vab', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Male\Jackaroo\JulianBuzz.vaj', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Male\Jackaroo\JulianBuzz.vam', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Male\Jackaroo\LeePompadour.jpg', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Male\Jackaroo\LeePompadour.vab', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Male\Jackaroo\LeePompadour.vaj', ` >> "%~dpn0.ps1"
echo            'Custom\Hair\Male\Jackaroo\LeePompadour.vam', ` >> "%~dpn0.ps1"
echo            'Custom\Scripts\MeshedVR', ` >> "%~dpn0.ps1"
echo            'Custom\Scripts\MeshedVR\CycleForce.cs', ` >> "%~dpn0.ps1"
echo            'Custom\Scripts\MeshedVR\FloatParamRandomizer.cs', ` >> "%~dpn0.ps1"
echo            'Custom\Scripts\MeshedVR\PluginBuilder.csproj', ` >> "%~dpn0.ps1"
echo            'Custom\Scripts\MeshedVR\PluginBuilder.sln', ` >> "%~dpn0.ps1"
echo            'Custom\Scripts\MeshedVR\ShowSelectedControllerHUD.cs', ` >> "%~dpn0.ps1"
echo            'Custom\Scripts\MeshedVR\Template.cs', ` >> "%~dpn0.ps1"
echo            'Custom\Scripts\MeshedVR\TemplateWithSamples.cs', ` >> "%~dpn0.ps1"
echo            'Custom\Scripts\MeshedVR\Test1.cs', ` >> "%~dpn0.ps1"
echo            'Custom\Scripts\MeshedVR\TriggerControl.cs', ` >> "%~dpn0.ps1"
echo            'Custom\Scripts\MeshedVR\TriggerControlSimple.cs', ` >> "%~dpn0.ps1"
echo            'Keys\1.20', ` >> "%~dpn0.ps1"
echo            'Keys\1.20\key.json', ` >> "%~dpn0.ps1"
echo            'Mono\EmbedRuntime', ` >> "%~dpn0.ps1"
echo            'Mono\etc', ` >> "%~dpn0.ps1"
echo            'Mono\EmbedRuntime\mono.dll', ` >> "%~dpn0.ps1"
echo            'Mono\EmbedRuntime\MonoPosixHelper.dll', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\1.0', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\2.0', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\mconfig', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\browscap.ini', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\config', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\1.0\DefaultWsdlHelpGenerator.aspx', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\1.0\machine.config', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\2.0\Browsers', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\2.0\DefaultWsdlHelpGenerator.aspx', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\2.0\machine.config', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\2.0\settings.map', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\2.0\web.config', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\2.0\Browsers\Compat.browser', ` >> "%~dpn0.ps1"
echo            'Mono\etc\mono\mconfig\config.xml', ` >> "%~dpn0.ps1"
echo            'Saves\scene', ` >> "%~dpn0.ps1"
echo            'Saves\scene\MeshedVR', ` >> "%~dpn0.ps1"
echo            'Saves\scene\MeshedVR\default.jpg', ` >> "%~dpn0.ps1"
echo            'Saves\scene\MeshedVR\default.json', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Resources', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\app.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\boot.config', ` >> "%~dpn0.ps1"
echo            'VaM_Data\globalgamemanagers', ` >> "%~dpn0.ps1"
echo            'VaM_Data\globalgamemanagers.assets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\level0', ` >> "%~dpn0.ps1"
echo            'VaM_Data\level1', ` >> "%~dpn0.ps1"
echo            'VaM_Data\level2', ` >> "%~dpn0.ps1"
echo            'VaM_Data\level3', ` >> "%~dpn0.ps1"
echo            'VaM_Data\level4', ` >> "%~dpn0.ps1"
echo            'VaM_Data\level5', ` >> "%~dpn0.ps1"
echo            'VaM_Data\level6', ` >> "%~dpn0.ps1"
echo            'VaM_Data\level7', ` >> "%~dpn0.ps1"
echo            'VaM_Data\level8', ` >> "%~dpn0.ps1"
echo            'VaM_Data\level9', ` >> "%~dpn0.ps1"
echo            'VaM_Data\resources.assets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\resources.assets.resS', ` >> "%~dpn0.ps1"
echo            'VaM_Data\sharedassets0.assets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\sharedassets1.assets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\sharedassets2.assets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\sharedassets3.assets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\sharedassets4.assets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\sharedassets5.assets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\sharedassets6.assets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\sharedassets7.assets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\sharedassets7.assets.resS', ` >> "%~dpn0.ps1"
echo            'VaM_Data\sharedassets8.assets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\sharedassets9.assets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\Accessibility.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\Assembly-CSharp.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\Assembly-UnityScript.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\Bass.Net.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\Boo.Lang.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\ICSharpCode.SharpZipLib.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\mcs.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\MHLab.PATCH.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\Mono.Cecil.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\Mono.Data.Tds.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\Mono.Posix.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\Mono.Security.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\Mono.WebBrowser.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\mscorlib.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\NAudio.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\protobuf-net.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\RTTypeModel.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\SteamVR.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\SteamVR_Actions.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\System.Configuration.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\System.Core.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\System.Data.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\System.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\System.Drawing.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\System.EnterpriseServices.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\System.Runtime.Serialization.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\System.Security.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\System.Transactions.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\System.Windows.Forms.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\System.Xml.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.AccessibilityModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.AccessibilityModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.AIModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.AIModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.AnimationModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.AnimationModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ARModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ARModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.AssetBundleModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.AssetBundleModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.AudioModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.AudioModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.BaselibModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.BaselibModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ClothModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ClothModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.CloudWebServicesModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.CloudWebServicesModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ClusterInputModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ClusterInputModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ClusterRendererModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ClusterRendererModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.CoreModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.CoreModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.CrashReportingModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.CrashReportingModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.DirectorModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.DirectorModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.FacebookModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.FacebookModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.GameCenterModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.GameCenterModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.GridModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.GridModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.HotReloadModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.HotReloadModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ImageConversionModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ImageConversionModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.IMGUIModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.IMGUIModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.InputModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.InputModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.JSONSerializeModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.JSONSerializeModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.Networking.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ParticlesLegacyModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ParticlesLegacyModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ParticleSystemModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ParticleSystemModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.PerformanceReportingModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.PerformanceReportingModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.Physics2DModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.Physics2DModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.PhysicsModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.PhysicsModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ScreenCaptureModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.ScreenCaptureModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.SharedInternalsModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.SharedInternalsModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.SpatialTracking.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.SpatialTrackingModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.SpatialTrackingModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.SpriteMaskModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.SpriteMaskModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.SpriteShapeModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.SpriteShapeModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.StyleSheetsModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.StyleSheetsModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.SubstanceModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.SubstanceModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.TerrainModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.TerrainModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.TerrainPhysicsModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.TerrainPhysicsModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.TextRenderingModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.TextRenderingModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.TilemapModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.TilemapModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.Timeline.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.TimelineModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.TimelineModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.TLSModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.TLSModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UI.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UIElementsModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UIElementsModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UIModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UIModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UmbraModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UmbraModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UNETModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UNETModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityAnalyticsModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityAnalyticsModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityConnectModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityConnectModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityWebRequestAssetBundleModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityWebRequestAssetBundleModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityWebRequestAudioModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityWebRequestModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityWebRequestModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityWebRequestTextureModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityWebRequestTextureModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.UnityWebRequestWWWModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.VehiclesModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.VehiclesModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.VideoModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.VideoModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.VRModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.VRModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.WebModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.WebModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.WindModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.WindModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.XRModule.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\UnityEngine.XRModule.xml', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\Valve.Newtonsoft.Json.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Managed\ZFBrowser.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\AudioPluginMsHRTF.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\AudioPluginOculusSpatializer.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\bass.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\cef.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\cef_100_percent.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\cef_200_percent.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\cef_extensions.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\chrome_elf.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\ConvexDecompositionDll.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\d3dcompiler_43.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\d3dcompiler_47.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\devtools_resources.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\icudtl.dat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\LeapC.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\libEGL.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\libGLESv2.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\libmpg123-0.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\libOni.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\natives_blob.bin', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\openvr_api.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\OVRGamepad.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\OVRLipSync.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\OVRPlugin.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\OVRVoiceMod.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\snapshot_blob.bin', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\ThirdPartyNotices.txt', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\widevinecdmadapter.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\ZFGameBrowser.exe', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\ZFProxyWeb.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\zf_cef.dll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\am.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\am.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ar.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ar.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\bg.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\bg.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\bn.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\bn.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ca.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ca.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\cs.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\cs.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\da.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\da.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\de.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\de.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\el.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\el.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\en-GB.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\en-GB.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\en-US.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\en-US.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\es-419.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\es-419.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\es.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\es.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\et.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\et.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\fa.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\fa.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\fi.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\fi.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\fil.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\fil.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\fr.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\fr.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\gu.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\gu.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\he.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\he.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\hi.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\hi.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\hr.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\hr.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\hu.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\hu.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\id.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\id.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\it.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\it.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ja.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ja.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\kn.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\kn.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ko.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ko.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\lt.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\lt.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\lv.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\lv.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ml.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ml.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\mr.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\mr.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ms.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ms.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\nb.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\nb.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\nl.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\nl.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\pl.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\pl.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\pt-BR.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\pt-BR.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\pt-PT.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\pt-PT.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ro.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ro.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ru.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ru.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\sk.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\sk.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\sl.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\sl.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\sr.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\sr.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\sv.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\sv.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\sw.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\sw.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ta.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\ta.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\te.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\te.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\th.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\th.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\tr.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\tr.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\uk.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\uk.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\vi.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\vi.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\zh-CN.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\zh-CN.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\zh-TW.pak', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Plugins\locales\zh-TW.pak.info', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Resources\browser_assets', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Resources\unity default resources', ` >> "%~dpn0.ps1"
echo            'VaM_Data\Resources\unity_builtin_extra', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_ani', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_apt', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_apt_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_cis', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_cis_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_cry', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_cry_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_cyb', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_cyb_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_cyb_mat2', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_cyb_mat3', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_ded', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_ded_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_drh', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_drh_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_dsb', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_dsb_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_faw', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_frc', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_isl', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_isl_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_lig', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_mis', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_mor', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_mor_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_ols', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_ols_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_per', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_per_anim', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_pro', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_ref', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_sha', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_sou', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_tec', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_tec_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_toy', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_tri', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_tri_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\a_vie', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_ai', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_ai_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_alk', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_alk_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_ave', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_ave_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_bas', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_bas_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_bll', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_bll_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_cad', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_cad_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_dae', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_dae_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_dat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_dat_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_err', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_err_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_gap', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_gap_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_har', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_har_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_heu', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_heu_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_hew', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_hew_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_hsg', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_hsg_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_ic', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_ic_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_lif', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_lif_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_lig', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_lig_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_mik', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_mik_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_mol', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_mol_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_neo', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_neo_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_nep', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_nep_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_noi', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_noi_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_oup', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_oup_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_rra', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_rra_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sab', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sab_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sed', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sed_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sfb', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sfb_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sip', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sip_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_skq', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_skq_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_so', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_so_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_spt', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_spt_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_stm', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_stm_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sug', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sug_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sw2', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sw2_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_swe', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_swe_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sy', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_sy_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_try', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_try_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_ucs', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_ucs_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_urm', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_urm_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_wd2', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\c_wd2_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_1', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_10', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_10_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_11', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_11_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_12', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_12_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_13', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_13_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_14', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_14_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_15', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_15_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_16', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_16_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_17', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_17_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_1_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_2', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_2_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_3', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_3_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_4', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_4_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_5', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_5_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_6', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_6_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_7', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_7_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_8', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_8_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_9', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_9_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_c', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_c_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_mb', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rcn', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rcn_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rev', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rev_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rjn', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rjn_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rky', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rky_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rlx', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rlx_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rma', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rma_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rmi', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rmi_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rsm', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rsm_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rta', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rta_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rti', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\f_rti_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_cha', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_cha_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_fan', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_fan_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_fli', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_fli_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_kra', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_kra_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_les', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_les_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_ley', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_ley_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_omr', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_omr_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_sco', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_sco_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_sg1', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_sg2', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_si2', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_si2m', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_si3', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_sol', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_sol_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_tyl', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_tyl_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_v5p_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\h_zzz_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_1', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_1_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_2', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_2_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_3', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_3_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_4', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_4_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_5', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_5_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_6', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_6_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_7', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_7_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_8', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_8_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_9', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_9_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_c', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_c_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_futi', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_futi_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_futk', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_futk_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_futl', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_futl_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_futm', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_futm_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_futs', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_futs_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_jjk', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_jjk_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_ljk', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_ljk_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\m_mb', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\p_eye_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\p_gen_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\p_sha_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\StandaloneWindows64', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\StandaloneWindows64.manifest', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\s_fem', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\s_mus', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\s_mus_cyb', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\s_per', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\s_set', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\s_sfx', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\s_toy', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\z_ben', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\z_cor', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\z_gen', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\z_msc_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\z_sha', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\z_sky_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\z_thu_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\z_ui1', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\z_ui2', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\z_ui_mat', ` >> "%~dpn0.ps1"
echo            'VaM_Data\StreamingAssets\z_vr_mat') >> "%~dpn0.ps1"

echo foreach($f in $FILES) { >> "%~dpn0.ps1"
echo   $s = $LINK ^| ? {$f.StartsWith($_)} >> "%~dpn0.ps1"
echo   if( $s ) { >> "%~dpn0.ps1"
echo     if( $s.EndsWith('\') ) { >> "%~dpn0.ps1"
echo       if( Test-Path -Path $f -PathType Leaf ) { >> "%~dpn0.ps1"
echo         New-Item -Path ('{0}\{1}' -f $DST,$f) -ItemType SymbolicLink -Value $f >> "%~dpn0.ps1"
echo       } else { >> "%~dpn0.ps1"
echo         New-Item -Path ('{0}\{1}' -f $DST,$f) -ItemType Directory >> "%~dpn0.ps1"
echo       } >> "%~dpn0.ps1"
echo     } elseif( $s -eq $f ) { >> "%~dpn0.ps1"
echo       New-Item -Path ('{0}\{1}' -f $DST,$f) -ItemType SymbolicLink -Value $f >> "%~dpn0.ps1"
echo     } >> "%~dpn0.ps1"
echo   } else { >> "%~dpn0.ps1"
echo     if( Test-Path -Path $f -PathType Container ) { >> "%~dpn0.ps1"
echo       New-Item -Path ('{0}\{1}' -f $DST,$f) -ItemType Directory >> "%~dpn0.ps1"
echo     } else { >> "%~dpn0.ps1"
echo       Copy-Item -Path $f -Destination ('{0}\{1}' -f $DST,$f) >> "%~dpn0.ps1"
echo     } >> "%~dpn0.ps1"
echo   } >> "%~dpn0.ps1"
echo } >> "%~dpn0.ps1"
echo. >> "%~dpn0.ps1"

echo foreach($f in ($DEFAULT_PACKAGES)) { >> "%~dpn0.ps1"
echo   New-Item -Path ("{0}\AddonPackages\{1}" -f $DST,$f) -ItemType SymbolicLink -Value (ls "AddonPackages\$f" -Recurse).FullName } >> "%~dpn0.ps1"

echo Add-Type -assembly "System.IO.Compression.FileSystem" >> "%~dpn0.ps1"
echo foreach($v in (ls ("{0}\AddonPackages\*.var" -f $DST))) { >> "%~dpn0.ps1"
echo   $z = [System.IO.Compression.ZipFile]::OpenRead($v.FullName) >> "%~dpn0.ps1"
echo   foreach($f in $z.Entries.FullName) { >> "%~dpn0.ps1"
echo     if($f -match "^saves/scene/.*\.(json|vac)$") { >> "%~dpn0.ps1"
echo       New-Item -Path ("{0}/AddonPackagesFilePrefs/{1}/{2}.hide" -f $DST,$v.BaseName,$f) -ItemType File -Force } } >> "%~dpn0.ps1"
echo   $z.Dispose() } >> "%~dpn0.ps1"

powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& \"%~dpn0.ps1\" \"%p%\""
del "%~dpn0.ps1"

:end
pause
